# Generated by Django 2.2.24 on 2024-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20240514_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
