# Generated by Django 2.2.24 on 2024-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20240514_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='parent',
            new_name='previous_evolution',
        ),
    ]
